services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000" # Host:Container Mapping
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge